on:
  workflow_call:

jobs:
  test:
    name: "Test ðŸ§ª"
    runs-on: ubuntu-latest
    container:
      image: node:24-alpine
    steps:
      - name: "Download build-tests artifact"
        uses: actions/download-artifact@v4
        with:
          name: artifacts-tests
          path: ./artifacts_tests

      - name: "Install tools ðŸ“¦"
        run: |
          apk add --no-cache \
            'mozjs~140'      \
            'nodejs~24'      \
            openjdk21-jre    \
            php84-cli

      - name: "Run tests ðŸ§©"
        working-directory: artifacts_tests
        run: |
          chmod +x ./wasm2lang_run_tests.sh
          SPIDERMONKEY_JS=/usr/bin/js140 ./wasm2lang_run_tests.sh
