name: "Wasm2Lang CI"

on:
  push:

jobs:
  build:
    name: "CI · Build"
    uses: ./.github/workflows/wasm2lang_build.yml

  test:
    name: "CI · Test"
    needs: build
    uses: ./.github/workflows/wasm2lang_test.yml
